(ns elenent.schema)

(def schema
  [{:db/ident :client/name
    :db/valueType :db.type/string
    :db/unique :db.unique/identity
    :db/cardinality :db.cardinality/one}
   {:db/ident :client/email
    :db/valueType :db.type/string
    :db/unique :db.unique/identity
    :db/cardinality :db.cardinality/one}
   {:db/ident :client/asset
    :db/valueType :db.type/ref
    :db/cardinality :db.cardinality/many}
   {:db/ident :client/contract
    :db/valueType :db.type/ref
    :db/cardinality :db.cardinality/many}
   {:db/ident :asset/breed
    :db/valueType :db.type/keyword
    :db/cardinality :db.cardinality/one}
   {:db/ident :asset/name
    :db/valueType :db.type/string
    :db/unique :db.unique/identity
    :db/cardinality :db.cardinality/one}
   {:db/ident :contract/name
    :db/valueType :db.type/string
    :db/unique :db.unique/identity
    :db/cardinality :db.cardinality/one}
   {:db/ident :contract/asset
    :db/valueType :db.type/ref
    :db/cardinality :db.cardinality/one}
   ])
