(ns elenent.model.underlying)

(def underlyings
  {:COMP "NASDAQ Composite Index"
   :DJIA "Dow Jones Industrial Average"
   :DJT "Dow Jones Transportation Average"
   :DJU "Dow Jones Utility Average Index"
   :GDOW "Global Dow Realtime"
   :IXCO "NASDAQ Computer Index"
   :MID "S&P 400 Mid Cap Index"
   :NDX "NASDAQ 100 Index (NASDAQ Calculation)"
   :NYA "NYSE Composite Index"
   :OEX "S&P 100 Index"
   :PSE "NYSE Arca Technology 100 Index"
   :RUI "Russell 1000 Index"
   :RUT "Russell 2000 Index"
   :SOX "PHLX Semiconductor Index"
   :SPX "S&P 500 Index"
   :XX-TNX "CBOE 10 Year Treasury Note Yield Index"
   :XX-TYX "CBOE 30 Year Treasury Bond Yield Index"
   :XAU "PHLX Gold/Silver Index"
   :XAX "NYSE American Composite Index"
   :XMI "NYSE Arca Major Market Index"
   :XX-XOI "NYSE Arca Oil Index"
   :FF "Fed Funds"
   :ED "Eurodollas"
   :TU "2-year Treasury Note"
   :FV "5-year Treasury Note"
   :TY "10-year Treasury Note"
   :US "30-year Treasury Note"})
